name: test

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  test:
    name: test on ruby-${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5' ]
        # ruby: [ '2.5', '2.6', '2.7' ]
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
        # include:
          # - ruby: '3.0'
            # os: 'ubuntu-latest'
            # experimental: true
          # - ruby: '3.0'
            # os: 'windows-latest'
            # experimental: true
          # - ruby: '3.0'
            # os: 'macos-latest'
            # experimental: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - if: matrix.os == 'macos-latest'
        run: brew install autoconf automake libtool

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake generate

      - run: bundle exec rake compile

      - run: bundle exec rspec
